name: Despliegue a GitHub Pages

on:
  push:
    branches:
      - master  # O 'main', si ese es el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalar dependencias (¡SOLUCIÓN FINAL!)
      - name: Install Dependencies (Forzado y No Interactivo)
        # --yes responde 'yes' a cualquier pregunta que haga npm, solucionando el error.
        run: npm ci --yes

      # 4. Construir la Aplicación
      - name: Build Angular Project
        run: npm run deploy:gh

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/proyecto-rosa-maria/browser
